src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Contract\EntityInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface, EntityInterface
{
    public const ROLE_ADMIN = 'ROLE_ADMIN';
    public const ROLE_USER = 'ROLE_USER';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank()
     * @Assert\Email(message="The email format is wrong.")
     */
    private ?string $email = null;

    /**
     * @var array<string>
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @var string|null The hashed password
     * @ORM\Column(type="string")
     * @Assert\NotBlank())
     */
    private ?string $password = null;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="createdBy")
     */
    private Collection $articles;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Profile", mappedBy="user", cascade={"persist", "remove"})
     */
    private ?Profile $profile = null;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    /**
     * @return array<string>
     */
    public static function getRoleList(): array
    {
        return [
            self::ROLE_USER,
            self::ROLE_ADMIN,
        ];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->getUserIdentifier();
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param array<string>|null $roles
     */
    public function setRoles(?array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getSalt(): string|null
    {
        return null;
    }

    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setCreatedBy($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->contains($article)) {
            $this->articles->removeElement($article);
            // set the owning side to null (unless already changed)
            if ($article->getCreatedBy() === $this) {
                $article->setCreatedBy(null);
            }
        }

        return $this;
    }

    public function getProfile(): ?Profile
    {
        return $this->profile;
    }

    public function setProfile(Profile $profile): self
    {
        $this->profile = $profile;

        // set the owning side of the relation if necessary
        if ($profile->getUser() !== $this) {
            $profile->setUser($this);
        }

        return $this;
    }
}

templates/_articles.html.twig
{% for idx, article in articles %}
    {% if idx%3 == 0 %}
        <div class="tile is-ancestor">
    {% endif %}

    <div class="tile is-4 is-parent">
        <div class="tile is-child card">
            <div class="card-image">
                {% if article.cover is not null %}
                    <figure class="image is-4by3">
                        <a href="{{ path('article', {'id': article.id}) }}">
                            <img src="{{ vich_uploader_asset(article.cover, 'mediaFile') }}"
                                 class="avis-image-link"
                                 alt="{{ article.cover.media.originalName }}"
                            >
                        </a>
                    </figure>
                {% endif %}
            </div>
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-3">
                            <a class="avis-link-green"
                               href="{{ path('article', {'id': article.id}) }}">
                                {{ article.title }}
                            </a>
                        </p>
                        <p class="subtitle">
                            <time class="is-size-6" datetime="{{ article.createdAt|date('Y-m-d') }}">
                                <i>{{ article.createdAt|date('Y-m-d H:h') }}</i>
                            </time>
                        </p>
                    </div>
                </div>

                <div class="content is-medium has-text-justified">
                    {{ article.caption }}
                    {% include '_tags.html.twig' with {'tags': article.tags} %}

                    - <span class="is-italic is-size-6">
                        {% trans %}label.by{% endtrans %} {{ article.createdBy.username }}
                    </span>
                </div>
            </div>
        </div>
    </div>

    {% if idx%3 == 2 or idx == articles|length-1 %}
        </div>
    {% endif %}
{% endfor %}

templates/_breadcrumb.html.twig
<nav class="breadcrumb avis-breadcrumb has-arrow-separator" aria-label="breadcrumbs">
    <ul>
        <li>
            <a class="avis-navbar-item" href="{{ path('homepage') }}">{% trans %}app.home_page.home{% endtrans %}</a>
        </li>
        {% for item in breadcrumb %}
            <li {% if item is iterable and item['isActive'] %}class="is-active"{% endif %}>
                {% if item is iterable %}
                    <a class="avis-navbar-item" href="{{ path(item['path'], {id: item['id']}) }}">
                        {{ item['label'] }}
                    </a>
                {% else %}
                    <span class="avis-breadcrumb-item">{{ item }}</span>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</nav>

templates/_error_notification.html.twig
<div class="notification is-danger avis-danger">
    {% if messageKey is defined %}
        {{ error.messageKey|trans(error.messageData) }}
    {% elseif message is defined %}
        {{ message|trans() }}
    {% endif %}
</div>

templates/_folders.html.twig
<div class="columns">
    <div class="column section">
        <div class="columns">
            <div class="column is-offset-2">
                {% for folder in folders %}
                    <div class="box">
                        <article class="media">
                            <div class="media-content">
                                <div class="content">
                                    {% if folder.articlePublished != 0 %}
                                    <a class="avis-link-green"
                                       href="{{ path('folder', {id: folder.id}) }}">
                                        {% endif %}
                                        <span class="icon is-large avis-2-5">
                                          {{ folder.icon|raw }}
                                        </span>
                                        <h1 class="title avis-color-inherit avis-folders-title">{{ folder.name }}</h1> -
                                        <span class="subtitle avis-color-inherit is-5 is-italic">
                                            {{ folder.articlePublished }}
                                            {% trans %}article.articles{% endtrans %}
                                        </span>
                                        {% if folder.articlePublished != 0 %}
                                    </a>
                                    {% endif %}
                                    <p class="has-text-justified">
                                        {{ folder.caption }}
                                    </p>
                                </div>
                            </div>
                        </article>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="column is-half avis-forest"></div>
</div>

templates/_footer.html.twig
<footer class="footer avis-footer">
    <div class="content has-text-centered">
        <p>
            <strong>Avis Indoctus</strong> {% trans %}app.footer.by{% endtrans %}
            <a class="avis-link-red" href="https://gitlab.com/Birdiz">
                <span class="icon avis-icon is-small is-left">
                    <i class="fab fa-gitlab"></i>
                </span>
                Birdiz
            </a> -

            {% trans %}app.footer.powered{% endtrans %}
            <a class="avis-link-red" href="https://symfony.com/" title="Symfony">
                <span class="icon avis-icon is-small is-left">
                  <i class="fab fa-symfony"></i>
                </span>
                Symfony
            </a>
        </p>

        <p>
            {% trans %}app.footer.icons{% endtrans %}
            <a class="avis-link-red" href="https://www.flaticon.com/authors/freepik" title="Freepik">
                Freepik
            </a>
            {% trans %}label.and{% endtrans %}
            <a class="avis-link-red" href="https://www.flaticon.com/authors/smashicons" title="Smashicons">
                Smashicons
            </a>
        </p>

        <p>
            {% if app.user %}
                <a href="{{ path('logout') }}" class="button is-light">
                    <span class="icon avis-icon is-small is-left">
                        <i class="fas fa-sign-out-alt"></i>
                    </span> &nbsp;
                    {% trans %}app.login.logout{% endtrans %}
                </a>
            {% else %}
                <a href="{{ path('login') }}" class="button is-light">
                    <span class="icon avis-icon is-small is-left">
                        <i class="fas fa-sign-in-alt"></i>
                    </span> &nbsp;
                    {% trans %}app.login.login{% endtrans %}
                </a>
            {% endif %}
        </p>
    </div>
</footer>

templates/_header.html.twig
<nav class="navbar has-shadow is-spaced avis-navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item avis-navbar-item" href="{{ path('homepage') }}">
                <span class="title is-4 avis-red">Avis Indoctus</span>
            </a>

            <a class="navbar-item avis-navbar-item" href="{{ path('contact') }}">
                <span class="icon avis-icon is-small is-left">
                    <i class="fas fa-feather"></i>
                </span>&nbsp;
                {% trans %}app.contact_page.contact{% endtrans %}
            </a>

            <a class="navbar-item avis-navbar-item" href="{{ path('newsletter') }}">
                <span class="icon avis-icon is-small is-left">
                    <i class="fas fa-envelope"></i>
                </span>&nbsp;
                {% trans %}app.newsletter_page.newsletter{% endtrans %}
            </a>
        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    {% if app.request.locale == 'de' %}
                        <a href="{{ path('homepage', {'_locale': 'fr'}) }}" class="button is-light">
                            <img src="{{ asset('build/images/france.ce81740b.svg') }}" alt="fr">
                        </a>
                    {% else %}
                        <a href="{{ path('homepage', {'_locale': 'de'}) }}" class="button is-light">
                            <img src="{{ asset('build/images/germany.652e718c.svg') }}" alt="de">
                        </a>
                    {% endif %}
                    {% if app.user and is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('admin_dashboard') }}" class="button is-light avis-admin-link">
                            <span class="icon avis-icon is-small is-left">
                                <i class="fas fa-user-cog"></i>
                            </span>&nbsp;&nbsp;
                            {% trans %}app.admin{% endtrans %}
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

</nav>

templates/_quote.html.twig
<div class="container">
    <div class="avis-effect avis-quote-effect">
        <div class="notification avis-quote">
            <div class="columns is-vcentered avis-effect__heading">
                <div class="column is-1 has-text-centered">
                    <span class="icon avis-green">
                      <i class="fas fa-2x fa-quote-left"></i>
                    </span>
                </div>
                <div class="column">
                    <p class="avis-quote content is-medium has-text-justified">
                        <span class="is-italic">{{ quote.quote }}</span>
                        &mdash;
                        <span class="has-text-weight-bold">{{ quote.author }}</span>
                    </p>
                </div>
            </div>
        </div>
        {% if quote.sources is not empty %}
            <div class="columns avis-effect__subheading">
                <div class="column">
                    <p class="content is-small">
                        {% for source in quote.sources %}
                            {{ source }}
                            <br/>
                        {% endfor %}
                    </p>
                </div>
            </div>
        {% endif %}
    </div>
</div>

templates/_tags.html.twig
{% for tag in tags %}
    <a class="avis-link-green" href="{{ path('article_search', {'slug': tag.slug}) }}">#{{ tag.slug }}</a>
{% endfor %}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Avis{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    {{ encore_entry_link_tags('app') }}
    {{ encore_entry_link_tags('media') }}
    {% block stylesheets %}{% endblock %}
</head>
<body>
{% include('_header.html.twig') %}

{% block body %}{% endblock %}

{% include('_footer.html.twig') %}
<script defer src="https://use.fontawesome.com/releases/v5.13.0/js/all.js"></script>
{{ encore_entry_script_tags('app') }}
{{ encore_entry_script_tags('bulma') }}
{% block javascripts %}{% endblock %}
</body>
</html>

templates/forms.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container is-fluid avis-forms">
        <div class="columns contact">
            <div class="column section">
                <div class="columns">
                    <div class="column is-half-desktop is-offset-one-quarter">
                        {% block form %}{% endblock %}
                    </div>
                </div>
            </div>
            <div class="column is-half"></div>
        </div>
    </div>
{% endblock %}